// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyyh1howWkWM-Tw5fHagrpjsHxkPqo0_I',
    appId: '1:898272517006:web:3ef1dc86061087c8ae22df',
    messagingSenderId: '898272517006',
    projectId: 'test-ee4d9',
    authDomain: 'test-ee4d9.firebaseapp.com',
    databaseURL: 'https://test-ee4d9-default-rtdb.firebaseio.com',
    storageBucket: 'test-ee4d9.appspot.com',
    measurementId: 'G-JRJ24CPYNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5YdYQaMWV9Z4NFccpKsApHNeiemguBIQ',
    appId: '1:898272517006:android:25340018cc310e4cae22df',
    messagingSenderId: '898272517006',
    projectId: 'test-ee4d9',
    databaseURL: 'https://test-ee4d9-default-rtdb.firebaseio.com',
    storageBucket: 'test-ee4d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcvciqMd8FwntiqzOwqDZcqtzawA6vnFI',
    appId: '1:898272517006:ios:64fb42871404e919ae22df',
    messagingSenderId: '898272517006',
    projectId: 'test-ee4d9',
    databaseURL: 'https://test-ee4d9-default-rtdb.firebaseio.com',
    storageBucket: 'test-ee4d9.appspot.com',
    androidClientId: '898272517006-8sggcu1b0qhklmciuc2fr4thfr95euqn.apps.googleusercontent.com',
    iosClientId: '898272517006-dc2qvnbq6t7d38ncegfqcl1l2a87q0qc.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomApp',
  );
}
